# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              CovidFAQ
description:        FAQ related to Covid-19 or Coronavirus
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:categories/:slug/
#permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.coms
url: "https://covidfaq.net"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo: images/logo/covidapi-logo-wo-text-tpnt.png
og-image: images/logo/covidfaq-logo-white-bg.jpg

logo-specs:
  desktop:
    width: 50px
    title: true
  mobile:
    width: 30px
    title: true

# Default author settings
author:
  name: Saiprasad Balasubramanian
  title: Software Developer
  avatar: "images/authors/sai.png"
  twitter: sai_cosmo

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  sid:
    name: Dr Siddharth Ramachandran
    title: Dr
    avatar: https://via.placeholder.com/80x80

  sai:
    name: Saiprasad Balasubramanian
    title: Software Developer
    avatar: "images/authors/sai.png"
    twitter: sai_cosmo

  harsh:
    name: Harsh Jain
    title: Software Developer
    avatar: "images/authors/harsh.png"
    twitter: hrkj_18

  anish:
    name: Anish Tipnis
    title: Software Developer
    avatar: "images/authors/anish.jpeg"
    twitter: rusty3699

  kalpesh:
    name: Kalpesh Rotkar
    title: Volunteer
    avatar: "images/authors/kalpesh.jpg"
    twitter:


# Social icons displayed in footer
social:
  email: team@covidfaq.net
  website: https://covidfaq.net
  facebook:
  flickr:
  dribbble:
  github: https://github.com/backtrackbaba/covid-faq
  googleplus:
  instagram:
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:

# Share button
share:
  post:           true # Display share buttons on a post page
  twitter:        true # Enable by adding Twitter handle
  facebook:       true # Enable by setting true (Facebook handle not required)
  whatsapp:       true

twitter:
  username: sai_cosmo


header:
  #  image: "http://localhost:5000/header-min.jpg"
  gradient: "background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
  #  background: "background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
  color: light
  search: true

# Default footer image settings
footer:
  copyright:      Made with ❤️ & ☕ by <a href="https://www.linkedin.com/in/saiprasadbala" target="_blank" rel="noreferrer">Saiprasad Balasubramanian</a> & <a href="https://www.linkedin.com/in/hrkj-18" target="_blank" rel="noreferrer">Harsh Jain</a>

# Disqus comments shortname, requires Disqus account https://disqus.com/
#disqus:
#  shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: UA-46861272-8

# Pagination Settings
pagination:
  enabled:          true
  per_page:         5
  # permalink: '/page/:num/'
  # title_suffix: ' - page :num'
  # limit: 0
  # sort_field: 'date'
  # sort_reverse: true

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-paginate-v2
  - jekyll-inline-svg
  - jekyll-purgecss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  faqs:
    output:         false
  #  changelogs:
  #    output:         false
#  understanding:
#    output: true
#  protecting-yourself:
#    output: true
#  medical-advice:
#    output: true
#  staying-safe:
#    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
      image: "images/logo/covidfaq-logo-white-bg.jpg"
  # _pages
  - scope:
      path:         ""
      type:         pages
    values:
      layout:       page

svg:
  optimize: true

css_dir: "assets/css"