# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              CovidFAQ
description:        FAQ related to Covid-19 or Coronavirus
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:categories/:slug/
#permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.coms
url: "https://covidfaq.net"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:

# Default author settings
author:
  name:           Saiprasad Balasubramanian
  title:          Lead Developer
  avatar:         https://via.placeholder.com/80x80
  twitter: sai_cosmo

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  sid:
    name:         Dr Siddharth Ramachandran
    title:        Dr
    avatar:       https://via.placeholder.com/80x80
  evan:
    name:         Evan Wells
    title:        Support
    avatar:       https://via.placeholder.com/80x80
  sara:
    name:         Sara Galen
    title:        Lead Developer
    avatar:       https://via.placeholder.com/80x80
  alex:
    name:         Alex Koch
    title:        Design Engineer
    avatar:       https://via.placeholder.com/80x80
  daniel:
    name:         Daniel Shultz
    title:        Developer
    avatar:       https://via.placeholder.com/80x80
  tom:
    name:         Tom Farrell
    title:        Developer
    avatar:       https://via.placeholder.com/80x80

# Social icons displayed in footer
social:
  email:
  website:
  facebook:       https://www.facebook.com/
  flickr:
  dribbble:
  github: https://github.com/backtrackbaba/covid-faq
  googleplus:
  instagram:      https://www.instagram.com/
  linkedin:
  pinterest:
  twitter:        https://twitter.com/
  vimeo:          https://vimeo.com/
  youtube:

# Share button
share:
  post:           true # Display share buttons on a post page
  twitter:        true # Enable by adding Twitter handle
  facebook:       true # Enable by setting true (Facebook handle not required)
  whatsapp:       true

twitter:
  username: sai_cosmo


header:
  #  image: "http://localhost:5000/header-min.jpg"
  gradient: "background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
  #  background: "background-image: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
  color: light
  search: true

# Default footer image settings
footer:
  copyright:      Made by with ❤️ by <a href="https://linkedin.com" target="_blank">Saiprasad Balasubramanian</a>

# Disqus comments shortname, requires Disqus account https://disqus.com/
#disqus:
#  shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Pagination Settings
pagination:
  enabled:          true
  per_page:         5
  # permalink: '/page/:num/'
  # title_suffix: ' - page :num'
  # limit: 0
  # sort_field: 'date'
  # sort_reverse: true

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-paginate-v2
  - jekyll-inline-svg

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  faqs:
    output:         false
  #  changelogs:
  #    output:         false
  understanding:
    output: true
  protecting-yourself:
    output: true
  medical-advice:
    output: true
  staying-safe:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _pages
  - scope:
      path:         ""
      type:         pages
    values:
      layout:       page

svg:
  optimize: true